package com.elepy.id;

import com.elepy.dao.Crud;

/**
 * Use this {@link IdentityProvider} if your ID gets generated by your database.
 * Eg: SQL AUTO Identity
 *
 * @param <T> The type of the Model
 */
public class NoIdentityProvider<T> implements IdentityProvider<T> {
    @Override
    public void provideId(T item, Crud<T> dao) {
        //The whole point of this is to provide no id ;P
    }
}
