package com.elepy.id;

import com.elepy.crud.Crud;

/**
 * Use this {@link IdentityProvider} if your ID gets generated by your database.
 * Eg: SQL AUTO Identity
 *
 */
public class NoIdentityProvider implements IdentityProvider {
    @Override
    public <T> void provideId(T item, Crud<T> dao) {
        //The whole point of this is to provide no id ;P
    }
}
